### ISSUE TITLE
TypeError: Cannot write to hid device

### ISSUE THREAD

**Issue by abshabab** [gamingdoom/beamng-shifting-leds#4]
After following the steps as listed, the terminal connects to BeamNG and runs into this error:

```
Connected to Logitech G29 wheel
Connected to BeamNG.Drive
C:\Users\My Name\Downloads\beamng-shifting-leds.js:81
    g29.write([0xf8, 0x12, LEDMask, 0x00, 0x00, 0x00, 0x01])
        ^

TypeError: Cannot write to hid device
    at updateLeds (C:\Users\My Name\Downloads\beamng-shifting-leds.js:81:9)
    at Socket.<anonymous> (C:\Users\Shabab Abedin\Downloads\beamng-shifting-leds.js:46:5)
    at Socket.emit (node:events:519:28)
    at UDP.onMessage [as onmessage] (node:dgram:942:8)
```
Not sure if this page is still maintained, just wondering if I followed the steps wrong or something...

P.S. - I am an absolute novice at programming, I created this Github account just now to post this issue because I want pretty lights in my game. Thanks in advance

**Comment by gamingdoom** [comment]
Could you try running the script in an administrator terminal?

Thanks.

**Comment by ThatGuyThimo** [comment]
same problem on windows, 
```
Connected to Logitech G29 wheel
Connected to BeamNG.Drive
Failed to write to HID device: TypeError: Cannot write to hid device
    at updateLeds (C:\Users\Thimo\Desktop\projects\beamng-shifting-leds\beamng-shifting-leds.js:84:15)
    at Socket.<anonymous> (C:\Users\Thimo\Desktop\projects\beamng-shifting-leds\beamng-shifting-leds.js:46:5)
    at Socket.emit (node:events:518:28)
    at UDP.onMessage [as onmessage] (node:dgram:941:8)
```

i modified the code a bit to catch the error

in updateLeds()
```
    if (g29) {
      try {
          g29.write([0xf8, 0x12, LEDMask, 0x00, 0x00, 0x00, 0x01]);
      } catch (e) {
          console.error("Failed to write to HID device:", e);
      }
  } else {
      console.error("HID device not initialized.");
  }
```

i checked the vid / pid and they are correct for my wheel
